### ISSUE TITLE
Version 1.1.0 seems to be missing from the maven-verse..

### ISSUE THREAD

**Issue by coding2012** [michel-kraemer/vertx-lang-typescript#3]
I see 1.2.0-SNAPSHOT and 1.0.0.
https://oss.sonatype.org/#nexus-search;quick~vertx-lang-typescript

It does seem however that version 1.0.0 is working just fine (just an older typescript I suppose).

**Comment by michel-kraemer** [comment]
Interesting. I'm pretty sure I uploaded the files. Nevertheless, I uploaded them again. Thanks for letting me know!

Cheers,
Michel
